server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9527/eureka #配置注册中心的地址
    register-with-eureka: false #此实例作为服务消费，不需要把自己注册到Eureka Server上

## 开启Feign中对hystrix的支持
feign:
  hystrix:
    enabled: true

## 服务提供方的应用名称
serviceName: shenyanming-user-provider