server:
  port: 80
spring:
  profiles:
    active: eureka #eureka、consul、nacos
  application:
    name: shenyanming-user-feign-consumer
  cloud:
    service-registry:
      auto-registration:
        enabled: false



## 自定义配置, 用来标识服务提供方的应用名称
sym:
  service:
    provider:
      name: shenyanming-user-provider
