## 在这里选择启用哪个注册中心
server:
  port: 80
spring:
  profiles:
    active: nacos
  application:
    name: shenyanming-user-feign-consumer
  cloud:
    service-registry:
      enabled: false # for consul自动配置类：ConsulServiceRegistryAutoConfiguration
      auto-registration:
        enabled: false


## 自定义配置, 用来标识服务提供方的应用名称
sym:
  service:
    provider:
      name: shenyanming-user-provider
