spring:
  cloud:
    consul:
      discovery:
        register: false
        service-name: springCloud-consumer
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
      host: 127.0.0.1
      port: 8500