eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka #配置注册中心的地址
    register-with-eureka: false #此实例作为服务消费，不需要把自己注册到Eureka Server上

# 自定义的配置项, 用于启动 eureka 的配置类
sym:
  eureka:
    enable: true