server:
  port: 13000
spring:
  application:
    name: shenyanmming-sleuth-service
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0 #采样比例设置为1.0，也就是全部都需要
  zipkin:
    base-url: http://localhost:9411 # 指定 zipkin server 的地址


## 自定义的服务名称
service:
  name: shenyanming-user-provider

## 连接eureka的地址
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:9527/eureka