server:
  port: 81
spring:
  profiles:
    active: consul #eureka、consul、nacos
  cloud:
    service-registry:
      auto-registration:
        enabled: false
  application:
    name: shenyanming-user-ribbon-consumer

## 自定义配置, 用来标识服务提供方的应用名称
sym:
  service:
    provider:
      name: shenyanming-user-provider
