server:
  port: 8001
spring:
  application:
    name: springCloud-provider
  profiles:
    active: consul
  ## 因为这个项目集成了多个注册中心, 所以需要将此配置关掉, 不然springCloud会自动加载
  ## 各个注册中心的自动配置类, 导致项目出现多个Bean而报错. 这边把它关掉, 自己配置
  cloud:
    service-registry:
      auto-registration:
        enabled: false



## 使用info结合springBoot的监管模块，可以向外部简单介绍本应用的情况
info:
  name: springCloud-provider-8001
  desc: 在8001端口暴露出服务
  company: com.sym

