server:
  port: 8001
spring:
  application:
    name: springCloud-provider
  profiles:
    active: eureka


## 使用info结合springBoot的监管模块，可以向外部简单介绍本应用的情况
info:
  name: springCloud-provider-8001
  desc: 在8001端口暴露出服务
  company: com.sym

