## 分布式配置中心Config服务端的配置
server:
  port: 10086
spring:
  application:
    name: config-server-10086
    index: 123214214 #作为唯一的ApplicationContextID
  cloud:
    config:
      server:
        git:
          ## github上存放配置文件的仓库SSH地址
          ##uri: git@github.com:sYmJoinGitHub/springcloud-config.git
          uri: https://github.com/sYmJoinGitHub/springcloud-config.git
          username:
          password:
    ## 开启记录消息总线bus的消息传播过程
    bus:
      trace:
        enabled: true
  ## 消息总线bus可以放在config-client配置，也可以放在config-server配置
  ## 当然最后还是放在config-server好一点
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
## 关闭权限验证
management:
  security:
    enabled: false

