server:
  port: 12580

## zuul需要作为一个微服务注册到Eureka中
spring:
  application:
    name: gateway-zuul
eureka:
  instance:
    prefer-ip-address: true
    instance-id: springcloud-zuul-12580
  client:
    service-url:
      defaultZone: http://127.0.0.1:9527/eureka
## 自定义路由映射规则
zuul:
  # routes是配置路由规则,它是一个Map类型,配置规则：<自定义>.serviceId => 服务名称，<自定义>.path => 访问映射
  routes:
    sym.serviceId: springCloud-provider
    sym.path: /sym/**
    sxq.serviceId: springCloud-provider
    sxq.path: /sxq/**
  # 配置不映射的服务ID（服务ID即注册在Eureka上面的服务名称）
  ignored-services: "*"
  # 映射前缀
  prefix: /springcloud



