# nacos相关配置
server:
  port: 8070
spring:
  application:
    name: nacos-demo
  cloud:
    nacos:
      # spring.cloud.discovery往下, 就是nacos服务注册与发现功能
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos server的地址(需要独立部署)
        registerEnabled: true #是否需要将本服务注册到nacos上, 若是服务消费方, 这个属性配置为false

# 自定义的配置
nacos:
  demo:
    content: '他日若遂凌云志, 敢笑黄泉不丈夫'