## 分布式配置中心Config服务端的配置
server:
  port: 10086
spring:
  application:
    name: config-server-10086
  cloud:
    config:
      server:
        git:
          ## github上存放配置文件的仓库SSH地址
          uri: git@github.com:sYmJoinGitHub/springcloud-config.git
