## 服务名
service:
  name: shenyanming-user-provider
server:
  port: 12581
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    gateway:
      routes:
        - id: test #自定义的id标识, 保持唯一性
          uri: http://www.baidu.com # 目标服务地址, 配置为服务名称, 依靠注册中心拉取IP地址
          predicates: # 路由判断条件, 使用的是JDK自带的Predicate断言类. 这边是当访问路径为/baidu时跳转到百度首页
            - Path=/baidu
        - id: prod
          uri: lb://shenyanming-user-provider
          predicates:
            - Path=/service/**
  application:
    name: shenyanmming-gateway-service

  main:
    allow-bean-definition-overriding: true
  profiles:
    active: eureka

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9527/eureka #配置注册中心的地址
    register-with-eureka: false #此实例作为服务消费，不需要把自己注册到Eureka Server上
    # 服务消费者启动时, 它会发送REST请求给Eureka注册中心, 获取在它上面注册的服务清单; Eureka Server会维护
    # 会维护一份只读的服务清单来返回给客户端, 该服务端清单每隔30秒更新一次, 关于获取服务清单有以下两个配置：
    fetch-registry: true # 为true时表示需要从Eureka Server获取服务清单
    registry-fetch-interval-seconds: 30 #默认情况下服务清单每隔30秒更新一次, 此配置可以修改它的更新间隔时间


