## 此工程的相关配置
server:
  port: 8002
spring:
  application:
    name: springCloud-provider
  profiles:
    active: eureka

## 使用info结合springBoot的监管模块，可以向外部简单介绍本应用的情况
info:
  name: springCloud-provider-8002
  desc: 在8002端口暴露出服务
  company: com.sym